"""Repository contracts."""

from __future__ import annotations

from typing import Protocol

from digital_employee.domain.approval import ApprovalRequest
from digital_employee.domain.events import LedgerEvent
from digital_employee.domain.session import SessionRecord
from digital_employee.domain.session import SessionProjection
from digital_employee.domain.work_order import WorkOrder


class WorkOrderRepository(Protocol):
    def create(self, work_order: WorkOrder) -> WorkOrder: ...

    def save(self, work_order: WorkOrder) -> WorkOrder: ...

    def get(self, work_order_id: str) -> WorkOrder | None: ...

    def list_all(self) -> list[WorkOrder]: ...


class SessionRepository(Protocol):
    def save(self, record: SessionRecord) -> SessionRecord: ...

    def get(self, session_id: str) -> SessionRecord | None: ...

    def list_all(self) -> list[SessionRecord]: ...


class EventLedgerRepository(Protocol):
    def append_all(self, events: list[LedgerEvent]) -> list[LedgerEvent]: ...

    def list_all(self) -> list[LedgerEvent]: ...

    def list_for_session(self, session_id: str) -> list[LedgerEvent]: ...

    def list_for_work_order(self, work_order_id: str) -> list[LedgerEvent]: ...


class SessionProjectionRepository(Protocol):
    def save(self, projection: SessionProjection) -> SessionProjection: ...

    def get(self, session_id: str) -> SessionProjection | None: ...

    def list_all(self) -> list[SessionProjection]: ...


class ApprovalRepository(Protocol):
    def create(self, approval: ApprovalRequest) -> ApprovalRequest: ...

    def save(self, approval: ApprovalRequest) -> ApprovalRequest: ...

    def get(self, approval_id: str) -> ApprovalRequest | None: ...

    def list_all(self) -> list[ApprovalRequest]: ...
